name: Release package

on:
  workflow_run:
    workflows: ["Unit testing"]
    branches: ["main"]
    types: ["completed"]

env:
  NODE_VERSION: 20.17.0

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache-dependency-path: './web/yarn.lock'
        cache: yarn
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      working-directory: ./web
      run: yarn
    - name: Publish
      working-directory: ./web
      run: |
        yarn build
        npm publish --provenance --access public --tag development
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}