name: Unit testing

on:
  push:

env:
  GO_VERSION: 1.23.1
  NODE_VERSION: 20.17.0

jobs:
  test_go:
    name: Unit test with Go
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-go
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install dependencies
        run: go get ./...
      - name: Test with Go
        run: go test -cover -coverprofile=coverage.txt ./...

  test_node:
    name: Unit test with Node
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-node
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: ./web
        run: yarn --frozen-lockfile
      - name: Test with Jest
        working-directory: ./web
        run: yarn test --coverage --passWithNoTests